export * from './model/types';
export { categoryOf, prettyIfcClass, CATEGORY_ORDER, CATEGORY_PLURAL } from './model/categories';
export { IfcClient, type OpenProgress } from './ifc/client';
export { Viewer, type ViewName, type ViewerEvents, type DisplayStyle, type SelectMode } from './render/Viewer';
export { parseCssColor } from './render/cssColor';
export { DxfClient } from './dxf/client';
export type { ParsedDrawing, DrawingInfo, DrawingLayer, DrawingText } from './dxf/types';
export { DrawingViewer, DEFAULT_DRAWING_DISPLAY, type DrawingViewerEvents, type DrawingDisplay, type DrawingTool, type CrosshairSize } from './render/DrawingViewer';
export { gridLevels, gridValues, GRID_MIN_PX, type GridLevel } from './render/drawingGrid';
export { indexEntities, objectTypeLabel, OBJECT_KIND, type EntityIndex } from './dxf/entityIndex';
export { resolvePalette, contrast } from './render/drawingColors';
export { DEFAULT_MARK_RULES, DEFAULT_GRADE_RULES, parseRules, rulePriority } from './ifc/marks';
export { buildBoq, type Boq, type BoqKey, type BoqRow } from './model/boq';
export { siFactor } from './ifc/quantities';
export { assessCompatibility, readViewDefinition, RECOMMENDED_EXPORT, type Compatibility, type CompatLevel } from './ifc/compat';
export { boxState, type SectionBoxState } from './render/sectionBox';
export type { CameraState } from './render/Viewer';
export type { Annotation } from './render/annotations';
export { EXPLODE_MODES, explodeOffsets, explodedBounds, type ExplodeMode } from './render/explode';
export type { PipelineSummary, PipelineLevel, PipelineQa } from './pipeline/types';
export type { PipelineOptions } from './dxf/protocol';
export { PYODIDE_VERSION, PYODIDE_INDEX_URL } from './pyodide';
export { History, Transaction, TransactionError, type Change, type CommittedTransaction } from './doc/transactions';
export { tempDims, type Dim2 } from './render/tempDims';
export { CURSOR, cursorsFor, isDarkColor, modifierCursor, type CursorSet } from './render/cursors';
export const ENGINE_VERSION = '0.25.0';
export { DEFAULT_CHECKS, QA_TOLERANCE, duplicatePairs, elementLabel, findingId, runChecks } from './qa/checks';
export type { Finding, QaCheck, QaContext, QaGroup, QaReport, Severity } from './qa/types';
